version: "3"

volumes:
  postgres_data: {}
  pgadmin_data: {}

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  backend:
    container_name: backend
    command: /start.sh
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    restart: on-failure
    env_file: .env

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8005:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: on-failure
    logging:
      driver: none
